language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t maracartman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true maracartman/react-test npm run test -- --coverage

after_success:
  - docker build -t maracartman/multi-client ./client
  - docker build -t maracartman/multi-nginx ./nginx
  - docker build -t maracartman/multi-server ./server
  - docker build -t maracartman/multi-worker ./worker
  # Log In into Docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker hub
  - docker push maracartman/multi-client
  - docker push maracartman/multi-nginx
  - docker push maracartman/multi-server
  - docker push maracartman/multi-worker